### ISSUE TITLE
"artisan config:publish" undefined

### ISSUE THREAD

**Issue by grcasanova** [npmweb/laravel-health-check#1]
config:publish undefined, using php artisan vendor:publish still triggers an error undefined package. Package installed through composer and added to providers.

**Comment by grcasanova** [comment]
A working solution:
<code>php artisan vendor:publish --provider="NpmWeb\LaravelHealthCheck\LaravelHealthCheckServiceProvider"</code>

**Comment by bandtank** [comment]
That returned the following message:

`Publishing complete for tag []!`

I don't know if that's right or not, but I also can't get it to work.
